[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && gunicorn -b 0.0.0.0:8000 app:app"
