"""Added category column to Flashcard

Revision ID: e7ca67efd951
Revises: 
Create Date: 2025-02-06 19:45:01.507361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ca67efd951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('mastered', sa.Boolean(), nullable=True))
        batch_op.drop_column('question')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('mastered')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
